server.port=8080

spring.application.name=gateway-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.mvc.routes[0].id=clientes-service
spring.cloud.gateway.mvc.routes[0].uri=lb://CLIENTES-SERVICE
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/clientes

spring.cloud.gateway.mvc.routes[1].id=productos-service
spring.cloud.gateway.mvc.routes[1].uri=lb://PRODUCTOS-SERVICE
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/productos

spring.cloud.gateway.mvc.routes[2].id=pedidos-service
spring.cloud.gateway.mvc.routes[2].uri=lb://PEDIDOS-SERVICE
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/pedidos